// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package persistence

type CartItem struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type Order struct {
	ID         string `json:"id"`
	TotalCents int32  `json:"total_cents"`
}

type OrderItem struct {
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type Product struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PriceCents int32  `json:"price_cents"`
	Stock      int32  `json:"stock"`
}
