// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package persistence

import (
	"context"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) error
	ClearCart(ctx context.Context) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	GetProduct(ctx context.Context, id string) (Product, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	ListCartItems(ctx context.Context) ([]CartItem, error)
	ReserveStock(ctx context.Context, arg ReserveStockParams) error
}

var _ Querier = (*Queries)(nil)
