// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package persistence

import (
	"context"
)

const addOrderItem = `-- name: AddOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type AddOrderItemParams struct {
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, addOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
`

func (q *Queries) ClearCart(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCart)
	return err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, total_cents)
VALUES ($1, $2)
`

type CreateOrderParams struct {
	ID         string `json:"id"`
	TotalCents int32  `json:"total_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder, arg.ID, arg.TotalCents)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_cents, stock
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (product_id, quantity)
VALUES ($1, $2)
`

type InsertCartItemParams struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem, arg.ProductID, arg.Quantity)
	return err
}

const listCartItems = `-- name: ListCartItems :many
SELECT product_id, quantity
FROM cart_items
ORDER BY product_id
`

func (q *Queries) ListCartItems(ctx context.Context) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveStock = `-- name: ReserveStock :exec
UPDATE products
SET stock = stock - $2
WHERE id = $1 AND stock >= $2
`

type ReserveStockParams struct {
	ID    string `json:"id"`
	Stock int32  `json:"stock"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) error {
	_, err := q.db.ExecContext(ctx, reserveStock, arg.ID, arg.Stock)
	return err
}
