services:
  postgres:
    container_name: gophercon-demo
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-adminuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gophercon
    ports:
      - "5433:5432"
    volumes:
      - gophercon-demo-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  gophercon-demo-data:
