// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const addOrderItem = `-- name: AddOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type AddOrderItemParams struct {
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, addOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
`

func (q *Queries) ClearCart(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCart)
	return err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, total_cents)
VALUES ($1, $2)
`

type CreateOrderParams struct {
	ID         string `json:"id"`
	TotalCents int32  `json:"total_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder, arg.ID, arg.TotalCents)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, price_cents, stock)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price_cents, stock
`

type CreateProductParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PriceCents int32  `json:"price_cents"`
	Stock      int32  `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.PriceCents,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, total_cents
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.TotalCents)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_cents, stock
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, name, price_cents, stock
FROM products
WHERE name = $1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO cart_items (product_id, quantity)
VALUES ($1, $2)
`

type InsertCartItemParams struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCartItem, arg.ProductID, arg.Quantity)
	return err
}

const listCartItems = `-- name: ListCartItems :many
SELECT product_id, quantity
FROM cart_items
ORDER BY product_id
`

func (q *Queries) ListCartItems(ctx context.Context) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT product_id, quantity
FROM order_items
WHERE order_id = $1
`

type ListOrderItemsRow struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]ListOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, total_cents
FROM orders
ORDER BY id
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_cents, stock
FROM products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveStock = `-- name: ReserveStock :exec
UPDATE products
SET stock = stock - $2
WHERE id = $1 AND stock >= $2
`

type ReserveStockParams struct {
	ID    string `json:"id"`
	Stock int32  `json:"stock"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) error {
	_, err := q.db.ExecContext(ctx, reserveStock, arg.ID, arg.Stock)
	return err
}
